version: 1
formatters:
  standard:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
loggers:
  jobs:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]